name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
    types: [ opened, synchronize, reopened ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Make the script files executable
        run: chmod +x my-script.sh
      # - name: Run the scripts
      #   run: |
      #     ./my-script.sh
      - name: Run File and collect logs
        id: run
        run:  |
          ./my-script.sh
          echo Running File...
          cat "../scripts/test.txt"
          status=$(echo ../scripts/test.txt)
          echo "{status}={$status}" >> $GITHUB_OUTPUT
      - name: Commit log
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git checkout HEAD
          git diff-index --quiet HEAD || git commit -am "deploy workflow logs"
          git push
      - name: Check run status
        if: steps.run.outputs.status != '0'
        run: exit "${{ steps.run.outputs.status }}"