name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
    types: [ opened, synchronize, reopened ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Make the script files executable
        run: chmod +x my-script.sh
      - name: Run the scripts
        run: |
          ./my-script.sh
      - name: Run File and collect logs
        id: run
        run:  |
          echo Running File...
          status=$(echo .github/scripts/test.txt)
          cat status.txt
          echo "{status}={$status}" >> $GITHUB_OUTPUT
      - name: Commit log
        run: |
          git add -A
          git checkout dev
          git diff-index --quiet HEAD || git commit -am "deploy workflow logs"
          git push
      - name: Check run status
        if: steps.run.outputs.status != '0'
        run: exit "${{ steps.run.outputs.status }}"